GUITAR_JOKES = [
    # Guitar puns
    "Tuning the tuner... 🎸",
    "Why did the guitar go to the doctor? It had a bad case of fret-itis!",
    "Stringing you along... ☕",
    "What's a guitarist's favorite coffee? Espresso yourself!",
    "Picking the right frequencies... 🎵",
    "Why don't guitars ever get lost? They always find their way back to the root note!",
    "Amplifying the experience... 🔊",
    "What do you call a guitar that never finishes a song? A quitter!",
    "Why did the guitarist get arrested? For fingering A minor!",
    "How do you make a guitarist play quieter? Put sheet music in front of them!",
    
    # Coffee + Guitar
    "Brewing some perfect pitch... ☕🎸",
    "This app runs on espresso and power chords!",
    "Caffeinating the frequencies...",
    "Why do guitarists love coffee? Because it helps them stay sharp!",
    "Grinding beans and grinding riffs...",
    "Latte art? More like guitar art!",
    "Espresso yourself through music!",
    "Coffee: The fuel of rock legends!",
    "Tuning with a side of cappuccino...",
    "Mocha-ing some sweet sounds!",
    
    # Assassin's Creed references
    "Nothing is true, everything is permitted... to be in tune! 🗡️",
    "Synchronizing with the Animus of sound...",
    "Leap of faith into perfect pitch!",
    "Hidden blade, hidden frequencies...",
    "Requiescat in pace... out of tune strings!",
    "The Creed: Always tune before you play!",
    "Eagle vision: Detecting flat notes!",
    "Assassinating bad intonation...",
    "Parkour through the fretboard!",
    "Ezio would approve of this tuning!",
    
    # Music theory jokes
    "Why was the guitar teacher arrested? For fingering A minor!",
    "What's the difference between a guitar and a fish? You can tune a guitar!",
    "How many guitarists does it take to change a lightbulb? Five - one to do it and four to say they could do it better!",
    "Why did the guitarist go broke? Too many frets!",
    "What do you call a beautiful woman on a guitarist's arm? A tattoo!",
    "How do you get a guitarist to stop playing? Put sheet music in front of them!",
    "What's the definition of perfect pitch? Throwing a banjo into a dumpster without hitting the rim!",
    "Why are guitar strings like parking spaces? All the good ones are taken!",
    "What do you call a guitarist without a girlfriend? Homeless!",
    "How can you tell if a stage is level? The guitarist drools from both sides of their mouth!",
    
    # Loading messages with humor
    "Calibrating the strings of destiny...",
    "Summoning the ghost of Jimi Hendrix...",
    "Consulting with the guitar gods...",
    "Polishing the frets of excellence...",
    "Warming up the amplifier of truth...",
    "Adjusting the bridge to enlightenment...",
    "Tightening the machine heads of wisdom...",
    "Plugging into the matrix of sound...",
    "Downloading sick riffs from the cloud...",
    "Initializing shred mode...",
    
    # More guitar puns
    "What's a guitar's favorite type of car? A Fender!",
    "Why did the guitar break up with the amp? Too much feedback!",
    "What do you call a cow that plays guitar? A moo-sician!",
    "Why don't guitars ever win at poker? They always show their hand!",
    "What's a guitarist's favorite vegetable? String beans!",
    "Why was the guitar cold? It left its case open!",
    "What do you call a guitar player who breaks up with their girlfriend? Homeless!",
    "Why did the guitar go to school? To get a little more class!",
    "What's a guitar's favorite exercise? Fret-ness training!",
    "Why don't guitars ever get tired? They're always amped up!",
    
    # Band jokes
    "What's the difference between a guitarist and a pizza? A pizza can feed a family of four!",
    "How do you know when a guitarist is at your door? They can't find the key and don't know when to come in!",
    "What do you call a guitarist who just broke up with their girlfriend? Homeless!",
    "Why do guitarists put drumsticks on their dashboard? So they can park in handicapped spaces!",
    "What's the difference between a guitar and a tuna fish? You can tune a guitar but you can't tuna fish!",
    "How many lead guitarists does it take to change a lightbulb? None - they just steal the bulb from the rhythm guitarist!",
    "What do you call a guitar player that only knows two chords? A music critic!",
    "Why did the guitarist get kicked out of the band? They were too high-strung!",
    "What's the range of a guitar? About 20 feet if you throw it hard enough!",
    "How do you make a guitarist's car more aerodynamic? Take the pizza delivery sign off the roof!",
    
    # Technical humor
    "Analyzing harmonic frequencies...",
    "Calculating the speed of sound... in coffee!",
    "Optimizing the Fourier transform...",
    "Calibrating the pitch detection algorithm...",
    "Synchronizing with the universal tuning standard...",
    "Initializing the chromatic scale...",
    "Loading the circle of fifths...",
    "Preparing the frequency spectrum analyzer...",
    "Tuning the Fast Fourier Transform...",
    "Activating perfect pitch mode...",
    
    # More coffee references
    "Percolating perfect pitch...",
    "Steaming up some sweet melodies...",
    "Frothing the frequencies...",
    "Brewing a strong cup of accuracy...",
    "Roasting those flat notes...",
    "Filtering out the bad vibes...",
    "Pouring precision into every note...",
    "Decaf? Never! Full-strength tuning only!",
    "Single origin tones, locally sourced!",
    "Fair trade frequencies for all!",
    
    # Legendary guitarists
    "Channeling the spirit of Eddie Van Halen...",
    "Consulting with Slash's top hat...",
    "Borrowing Eric Clapton's precision...",
    "Summoning Stevie Ray Vaughan's soul...",
    "Asking Jimmy Page for guidance...",
    "Learning from B.B. King's wisdom...",
    "Stealing licks from Chuck Berry...",
    "Invoking the power of Hendrix...",
    "Tuning like Django Reinhardt...",
    "Channeling Carlos Santana's smooth tones...",
]